name: Update Submodule and Deploy

on:
  push:
    branches:
      - main
    paths:
      - Research/**
  workflow_dispatch:

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout study-hub repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # 서브모듈도 포함해서 체크아웃

      - name: Set up Git user
        run: |
          git config --global user.name "choyeun"
          git config --global user.email "choyeun0372@gmail.com"

      - name: Update Submodule to Latest Commit
        run: git submodule update --init --recursive

      - name: Commit Updated Submodule
        run: |
          git add .
          git commit -m "Update submodule to latest local commit"
          git push

      - name: Install Dependencies
        run: npm install

      - name: Deploy the Site
        run: npm run deploy
        env:
          GIT_USER: choyeun
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}