name: Deploy on Study Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
    paths:
      - '.gitmodules'

jobs:
  update-submodule-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout study-hub repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update Submodule to Latest Commit
        run: git submodule foreach git pull origin main

      - name: Commit Submodule Update
        run: |
          git add .
          git commit -m "Update submodule to latest commit"
          git push

      - name: Install Dependencies
        run: npm install

      - name: Run Deploy
        run: npm run deploy
        env:
          GIT_USER: choyeun
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}