name: Hourly Deploy

on:
  schedule:
    - cron: '0 * * * *'  # 매 정시(0분)에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # 액세스 토큰을 사용하여 체크아웃

      - name: Set up Git user
        run: |
          git config --global user.name "choyeun"
          git config --global user.email "choyeun0372@gmail.com"

      - name: Update Submodule to Latest Commit
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Commit Updated Submodule
        run: |
          git add Research
          git commit -m "Update submodule to latest local commit" || echo "No changes to commit"
          git push || echo "Nothing to push"
        env:
          GIT_USER: choyeun
          GITHUB_TOKEN: ${{ secrets.PAT }}  # 푸시할 때도 토큰 사용
